version: '2'
services:
  app:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:password@mysql:3306
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/eStreak
    links:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '4306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  chrome:
    image: selenium/standalone-chrome:3.141.59-dubnium
    ports:
      - 4444:4444
volumes:
  mysql-data:
    driver: local
